# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_prefs\RnD\maya\python\OTHER\pluginLoader\pluginLoader.ui'
#
# Created: Mon Feb 16 11:44:27 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pluginLoader(object):
    def setupUi(self, pluginLoader):
        pluginLoader.setObjectName(_fromUtf8("pluginLoader"))
        pluginLoader.resize(416, 388)
        self.centralwidget = QtGui.QWidget(pluginLoader)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pluginPath_led = QtGui.QLineEdit(self.groupBox)
        self.pluginPath_led.setObjectName(_fromUtf8("pluginPath_led"))
        self.horizontalLayout.addWidget(self.pluginPath_led)
        self.pluginInfo_btn = QtGui.QPushButton(self.groupBox)
        self.pluginInfo_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.pluginInfo_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pluginInfo_btn.setObjectName(_fromUtf8("pluginInfo_btn"))
        self.horizontalLayout.addWidget(self.pluginInfo_btn)
        self.pluginBrowse_btn = QtGui.QPushButton(self.groupBox)
        self.pluginBrowse_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.pluginBrowse_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pluginBrowse_btn.setObjectName(_fromUtf8("pluginBrowse_btn"))
        self.horizontalLayout.addWidget(self.pluginBrowse_btn)
        self.pluginRemove_btn = QtGui.QPushButton(self.groupBox)
        self.pluginRemove_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.pluginRemove_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pluginRemove_btn.setObjectName(_fromUtf8("pluginRemove_btn"))
        self.horizontalLayout.addWidget(self.pluginRemove_btn)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setMargin(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loadScene_cbx = QtGui.QCheckBox(self.groupBox_2)
        self.loadScene_cbx.setText(_fromUtf8(""))
        self.loadScene_cbx.setChecked(True)
        self.loadScene_cbx.setObjectName(_fromUtf8("loadScene_cbx"))
        self.horizontalLayout_2.addWidget(self.loadScene_cbx)
        self.scenePath_led = QtGui.QLineEdit(self.groupBox_2)
        self.scenePath_led.setObjectName(_fromUtf8("scenePath_led"))
        self.horizontalLayout_2.addWidget(self.scenePath_led)
        self.setCurrentScene_btn = QtGui.QPushButton(self.groupBox_2)
        self.setCurrentScene_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.setCurrentScene_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.setCurrentScene_btn.setObjectName(_fromUtf8("setCurrentScene_btn"))
        self.horizontalLayout_2.addWidget(self.setCurrentScene_btn)
        self.sceneBrowse_btn = QtGui.QPushButton(self.groupBox_2)
        self.sceneBrowse_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.sceneBrowse_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sceneBrowse_btn.setObjectName(_fromUtf8("sceneBrowse_btn"))
        self.horizontalLayout_2.addWidget(self.sceneBrowse_btn)
        self.sceneremove_btn = QtGui.QPushButton(self.groupBox_2)
        self.sceneremove_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.sceneremove_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sceneremove_btn.setObjectName(_fromUtf8("sceneremove_btn"))
        self.horizontalLayout_2.addWidget(self.sceneremove_btn)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setMargin(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.scriptEditor_ly = QtGui.QVBoxLayout()
        self.scriptEditor_ly.setSpacing(0)
        self.scriptEditor_ly.setObjectName(_fromUtf8("scriptEditor_ly"))
        self.horizontalLayout_3.addLayout(self.scriptEditor_ly)
        self.eval_btn = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eval_btn.sizePolicy().hasHeightForWidth())
        self.eval_btn.setSizePolicy(sizePolicy)
        self.eval_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.eval_btn.setObjectName(_fromUtf8("eval_btn"))
        self.horizontalLayout_3.addWidget(self.eval_btn)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.load_btn = QtGui.QPushButton(self.centralwidget)
        self.load_btn.setObjectName(_fromUtf8("load_btn"))
        self.gridLayout.addWidget(self.load_btn, 0, 0, 1, 1)
        self.reload_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reload_btn.sizePolicy().hasHeightForWidth())
        self.reload_btn.setSizePolicy(sizePolicy)
        self.reload_btn.setObjectName(_fromUtf8("reload_btn"))
        self.gridLayout.addWidget(self.reload_btn, 0, 1, 2, 1)
        self.unload_btn = QtGui.QPushButton(self.centralwidget)
        self.unload_btn.setObjectName(_fromUtf8("unload_btn"))
        self.gridLayout.addWidget(self.unload_btn, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        pluginLoader.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(pluginLoader)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        pluginLoader.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(pluginLoader)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        pluginLoader.setMenuBar(self.menuBar)
        self.openSettings_act = QtGui.QAction(pluginLoader)
        self.openSettings_act.setObjectName(_fromUtf8("openSettings_act"))
        self.quit_act = QtGui.QAction(pluginLoader)
        self.quit_act.setObjectName(_fromUtf8("quit_act"))
        self.actionClear_settings = QtGui.QAction(pluginLoader)
        self.actionClear_settings.setObjectName(_fromUtf8("actionClear_settings"))
        self.menuFile.addAction(self.openSettings_act)
        self.menuFile.addAction(self.quit_act)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(pluginLoader)
        QtCore.QMetaObject.connectSlotsByName(pluginLoader)

    def retranslateUi(self, pluginLoader):
        pluginLoader.setWindowTitle(_translate("pluginLoader", "MainWindow", None))
        self.groupBox.setTitle(_translate("pluginLoader", "Plugin", None))
        self.pluginInfo_btn.setText(_translate("pluginLoader", "inf", None))
        self.pluginBrowse_btn.setText(_translate("pluginLoader", "Add", None))
        self.pluginRemove_btn.setText(_translate("pluginLoader", "Del", None))
        self.groupBox_2.setTitle(_translate("pluginLoader", "Scene", None))
        self.setCurrentScene_btn.setText(_translate("pluginLoader", "Curr", None))
        self.sceneBrowse_btn.setText(_translate("pluginLoader", "Add", None))
        self.sceneremove_btn.setText(_translate("pluginLoader", "Del", None))
        self.groupBox_3.setTitle(_translate("pluginLoader", "Script", None))
        self.eval_btn.setText(_translate("pluginLoader", ">", None))
        self.load_btn.setText(_translate("pluginLoader", "Load", None))
        self.reload_btn.setText(_translate("pluginLoader", "Reload", None))
        self.unload_btn.setText(_translate("pluginLoader", "Unload", None))
        self.menuFile.setTitle(_translate("pluginLoader", "File", None))
        self.openSettings_act.setText(_translate("pluginLoader", "Open settings file", None))
        self.quit_act.setText(_translate("pluginLoader", "Quit", None))
        self.actionClear_settings.setText(_translate("pluginLoader", "Clear settings", None))

