# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_pipeline\pw_pipeline\assets\maya\python\TOOLS\pw_mayaPluginLoader\pw_maya_plugin_loader\pluginLoader.ui'
#
# Created: Sat Nov  3 20:33:21 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_pluginLoader(object):
    def setupUi(self, pluginLoader):
        pluginLoader.setObjectName("pluginLoader")
        pluginLoader.resize(416, 388)
        self.centralwidget = QtWidgets.QWidget(pluginLoader)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pluginPath_led = QtWidgets.QLineEdit(self.groupBox)
        self.pluginPath_led.setObjectName("pluginPath_led")
        self.horizontalLayout.addWidget(self.pluginPath_led)
        self.pluginInfo_btn = QtWidgets.QPushButton(self.groupBox)
        self.pluginInfo_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.pluginInfo_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pluginInfo_btn.setObjectName("pluginInfo_btn")
        self.horizontalLayout.addWidget(self.pluginInfo_btn)
        self.pluginBrowse_btn = QtWidgets.QPushButton(self.groupBox)
        self.pluginBrowse_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.pluginBrowse_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pluginBrowse_btn.setObjectName("pluginBrowse_btn")
        self.horizontalLayout.addWidget(self.pluginBrowse_btn)
        self.pluginRemove_btn = QtWidgets.QPushButton(self.groupBox)
        self.pluginRemove_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.pluginRemove_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pluginRemove_btn.setObjectName("pluginRemove_btn")
        self.horizontalLayout.addWidget(self.pluginRemove_btn)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadScene_cbx = QtWidgets.QCheckBox(self.groupBox_2)
        self.loadScene_cbx.setText("")
        self.loadScene_cbx.setChecked(True)
        self.loadScene_cbx.setObjectName("loadScene_cbx")
        self.horizontalLayout_2.addWidget(self.loadScene_cbx)
        self.scenePath_led = QtWidgets.QLineEdit(self.groupBox_2)
        self.scenePath_led.setObjectName("scenePath_led")
        self.horizontalLayout_2.addWidget(self.scenePath_led)
        self.setCurrentScene_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.setCurrentScene_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.setCurrentScene_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.setCurrentScene_btn.setObjectName("setCurrentScene_btn")
        self.horizontalLayout_2.addWidget(self.setCurrentScene_btn)
        self.sceneBrowse_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.sceneBrowse_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.sceneBrowse_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sceneBrowse_btn.setObjectName("sceneBrowse_btn")
        self.horizontalLayout_2.addWidget(self.sceneBrowse_btn)
        self.sceneremove_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.sceneremove_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.sceneremove_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sceneremove_btn.setObjectName("sceneremove_btn")
        self.horizontalLayout_2.addWidget(self.sceneremove_btn)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scriptEditor_ly = QtWidgets.QVBoxLayout()
        self.scriptEditor_ly.setSpacing(0)
        self.scriptEditor_ly.setObjectName("scriptEditor_ly")
        self.horizontalLayout_3.addLayout(self.scriptEditor_ly)
        self.eval_btn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eval_btn.sizePolicy().hasHeightForWidth())
        self.eval_btn.setSizePolicy(sizePolicy)
        self.eval_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.eval_btn.setObjectName("eval_btn")
        self.horizontalLayout_3.addWidget(self.eval_btn)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setObjectName("load_btn")
        self.gridLayout.addWidget(self.load_btn, 0, 0, 1, 1)
        self.reload_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reload_btn.sizePolicy().hasHeightForWidth())
        self.reload_btn.setSizePolicy(sizePolicy)
        self.reload_btn.setObjectName("reload_btn")
        self.gridLayout.addWidget(self.reload_btn, 0, 1, 2, 1)
        self.unload_btn = QtWidgets.QPushButton(self.centralwidget)
        self.unload_btn.setObjectName("unload_btn")
        self.gridLayout.addWidget(self.unload_btn, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        pluginLoader.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(pluginLoader)
        self.statusbar.setObjectName("statusbar")
        pluginLoader.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(pluginLoader)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        pluginLoader.setMenuBar(self.menuBar)
        self.openSettings_act = QtWidgets.QAction(pluginLoader)
        self.openSettings_act.setObjectName("openSettings_act")
        self.quit_act = QtWidgets.QAction(pluginLoader)
        self.quit_act.setObjectName("quit_act")
        self.actionClear_settings = QtWidgets.QAction(pluginLoader)
        self.actionClear_settings.setObjectName("actionClear_settings")
        self.menuFile.addAction(self.openSettings_act)
        self.menuFile.addAction(self.quit_act)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(pluginLoader)
        QtCore.QMetaObject.connectSlotsByName(pluginLoader)

    def retranslateUi(self, pluginLoader):
        pluginLoader.setWindowTitle(QtWidgets.QApplication.translate("pluginLoader", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("pluginLoader", "Plugin", None, -1))
        self.pluginInfo_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "inf", None, -1))
        self.pluginBrowse_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Add", None, -1))
        self.pluginRemove_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Del", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("pluginLoader", "Scene", None, -1))
        self.setCurrentScene_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Curr", None, -1))
        self.sceneBrowse_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Add", None, -1))
        self.sceneremove_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Del", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("pluginLoader", "Script", None, -1))
        self.eval_btn.setText(QtWidgets.QApplication.translate("pluginLoader", ">", None, -1))
        self.load_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Load", None, -1))
        self.reload_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Reload", None, -1))
        self.unload_btn.setText(QtWidgets.QApplication.translate("pluginLoader", "Unload", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("pluginLoader", "File", None, -1))
        self.openSettings_act.setText(QtWidgets.QApplication.translate("pluginLoader", "Open settings file", None, -1))
        self.quit_act.setText(QtWidgets.QApplication.translate("pluginLoader", "Quit", None, -1))
        self.actionClear_settings.setText(QtWidgets.QApplication.translate("pluginLoader", "Clear settings", None, -1))

